name: Our workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v6
        with:
          path: our-source
      - run: ls -al our-source
      - run: cat our-source/.github/workflows/checkout.yml
